[project]
name = "llm-playground"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "zzc235", email = "145137715+zzc235@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openai>=3.14.0",
    "python-dotenv>=1.2.3",
    "tenacity>=9.1.4",
]

[project.scripts]
llm-playground = "llm_playground:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
